#!/bin/bash

# Smart cat: calls cat, zcat, or bzcat on each of a list of files, as
# appropriate.
# Source: Joshua

cat_cmd="cat"

for file in $@; do
    f_res=$(file -Li "$file" | perl -pe 's/^\S+: [^\/]+\/(x\-)?(\S+);.*$/$2/;');
    case "$f_res" in 
	bzip2)
	    cat_cmd=bzcat
	    ;;
	gzip)
	    cat_cmd=zcat
	    ;;
	*)
	    cat_cmd=cat
	    ;;
    esac
    $cat_cmd "$file"
done
